---
title: "FBD measurements"
author: "Leah Crowe"
output: pdf_document
bibliography: references.bib
---

```{r setup, include=FALSE}
library(dplyr)
library(lubridate)
library(stringr)
library(readxl)
library(ggplot2)
library(ggpubr)

# Data ----
#add population variable to datasheet
#write code to merge data xlsx from Whalelength

#grabs all alts from altperimage files
path<-"./Images/"

measurement_list <- list.files(path, glob2rx("altperimage*.xlsx"), ignore.case = TRUE, recursive = TRUE)

measurement_files <-
  lapply(measurement_list, function(x)
    read_excel(paste0(path, x)))

measurement_files_filter<-lapply(measurement_files, function(x)
  
  x%>%
    filter(issue == 'N' & !is.na(actual_length))%>%
    distinct(DATE, vlc_filename, ID, actual_length)%>% #avg_length_mean, avg_length_sd)
    mutate(trip = paste0(year(DATE),"_",month(DATE)))%>%
    mutate(trip = str_replace(trip, "_7", "_07"))%>%
    mutate(trip = str_replace(trip, "2023_5", "2023_05"))%>%
    mutate(trip = str_replace(trip, "2023_6", "2023_06"))%>%
    mutate(trip = str_replace(trip, "2022_5", "2022_05"))%>%
    mutate(trip = case_when(
      trip == "2023_1" ~ str_replace(trip, "2023_1", "2023_01"),
      TRUE ~ trip))
  )

measurement_merge <- bind_rows(measurement_files_filter)%>%
    mutate(ID = case_when(
    ID == "noodle" ~ "calibration",
    TRUE ~ ID
  ))

#number measurements
nrow(measurement_merge)

measurement_ID_trip<-measurement_merge%>%
  ungroup()%>%
  dplyr::select(ID, actual_length, trip)

measurement_merge%>%
  filter(ID == 'SUNSHINE')
```

```{r, whalength_file_merge}

source('./whalength_file_merge.R', local = TRUE, verbose = F)$value
head(length_ID_merge_Tt)

measure_data<-length_ID_merge_Tt%>%
  filter(issue == "N")%>%
  dplyr::select(ID, trip, YEAR, DATE, Filename, "tilt_wl" = Tilt..degrees., "alt_corrected" = Corrected.height..m., "length_wl" = Total.Length..m.,
                "w10" = Width.at.10..TL, "w20" = Width.at.20..TL, "w30" = Width.at.30..TL, "w40" = Width.at.40..TL, "w50" = Width.at.50..TL,
                "w60" = Width.at.10..TL, "w70" = Width.at.20..TL, "w80" = Width.at.30..TL, "w90" = Width.at.40..TL, Rostrum.BH, Fluke.width, 
                "BHDF" = BH.DF.insertion, COMMENTS, tilt_deg, laser_altitude_m, actual_length)


length_data<-measure_data%>%
  filter(!is.na(length_wl))

#number of measurements done, includes unmatched
nrow(length_data)
#checking that correct tilt was entered in whalength for measurement
length_data%>%
  filter(tilt_wl != tilt_deg)%>%
  dplyr::select(ID, trip, DATE, Filename, tilt_wl, tilt_deg)

#checking that length measured in whalength was the same that I entered
length_data%>%
  mutate(diff_tl = length_wl - actual_length)%>%
  filter(diff_tl > 0.001)%>%
  dplyr::select(ID, trip, DATE, Filename, length_wl, actual_length)

# length_data%>%
#   dplyr::select(alt_corrected, laser_altitude_m)

length_data<-length_data%>%
  mutate(length_use = case_when(
    !is.na(actual_length) ~ length_wl,
    TRUE ~ NA
  ))

```


```{r demo, include = F}
# life history update ----

source('C:/Users/leahm/OneDrive - University of Otago/Documents/git-otago/Fiordland_reporting/scripts/life_history_ageclass update.R', local = TRUE, verbose = F)$value
#use below when you can write to db again
#lifehist<-dbReadTable(con, "life_history_ageclass")
#this created from life_history_ageclass update.R
lifehist<-lifehist

lifehist%>%
  filter(NAME == "SUNSHINE")
# merge lh with measurements ----

measurements_demo_ind<-length_data%>%
  filter(ID != 'calibration')%>%
  filter(ID != 'COMMON')%>%
  left_join(lifehist, by = c('ID' = 'NAME'))%>%
  mutate(YEAR = case_when(
    as.numeric(str_sub(trip,6,7)) < 9 ~ as.numeric(str_sub(trip,1,4)),
    as.numeric(str_sub(trip,6,7)) >= 9 ~ as.numeric(str_sub(trip,1,4))+1,
  ))%>%
  mutate(month = as.numeric(str_sub(trip,6,7)))%>%
  dplyr::select(trip, YEAR, ID, length_use, SEX, BIRTH_YEAR, FIRST_YEAR, FIRST_CALF, ends_with('2022'), ends_with('2023'), ends_with('2024'), POD, month)%>%
  #tidyr::pivot_longer(cols = starts_with("X"), names_to = "AGECLASS_YEAR", values_to = "AGECLASS")%>%
  tidyr::pivot_longer(cols = starts_with("2"), names_to = "AGECLASS_YEAR", values_to = "AGECLASS")%>%
  mutate(AGECLASS_YEAR = str_replace(AGECLASS_YEAR, "X", ""))%>%
  filter(YEAR == AGECLASS_YEAR)%>%
  #dplyr::rename(AGECLASS = ends_with(YEAR))%>%
  mutate(AGECLASS = case_when(
    ID == "SUNSHINE" ~ "C",
    TRUE ~ AGECLASS
  ))%>%
  mutate(trip = case_when(
    trip == "2023_06" & POD == "DOUBTFUL" ~ "2023_07",
    TRUE ~ trip
  ))

#measurements_demo_ind%>%filter(trip == "2023_06" & POD == "DOUBTFUL")

measurements_demo_ind$AGECLASS<-factor(measurements_demo_ind$AGECLASS, levels = c("C","J","S-A","A"))

# only age grouping ----

age_length<-measurements_demo_ind

age_length$BIRTH_YEAR<-as.numeric(age_length$BIRTH_YEAR)
age_length$FIRST_YEAR<-as.numeric(age_length$FIRST_YEAR)
age_length$YEAR<-as.numeric(age_length$YEAR)

age_calc<-age_length%>%
  ungroup()%>%
  mutate(age = case_when(
    !is.na(BIRTH_YEAR) ~ YEAR-BIRTH_YEAR,
    is.na(BIRTH_YEAR) ~ YEAR-FIRST_YEAR #min_age
  ))%>%
  mutate(age_value = case_when(
    !is.na(BIRTH_YEAR) ~ "actual", #birth year known
    is.na(BIRTH_YEAR) ~ "min" #birth year not known
  ))%>%
  filter(!is.na(age)) # gets ride of unmatched dolphin measurements
```

```{r age_length, echo = F, message = F}

age_calc<-age_calc%>%
  #give a better approximation of age for older reproductive females?
  mutate(age = case_when(
    age_value == "min" & !is.na(FIRST_CALF) ~ age + (avg_primo_age - (as.numeric(FIRST_CALF) - as.numeric(FIRST_YEAR))),
    TRUE ~ age
  ))%>%
  mutate(age_month = case_when(
    month == 9 ~ age + 0,
    month == 10 ~ age + 1/12,
    month == 11 ~ age + 2/12,
    month == 12 ~ age + 3/12,
    month == 1 ~ age + 4/12,
    month == 2 ~ age + 5/12,
    month == 3 ~ age + 6/12,
    month == 4 ~ age + 7/12,
    month == 5 ~ age + 8/12,
    month == 6 ~ age + 9/12,
    month == 7 ~ age + 10/12,
    month == 8 ~ age + 11/12,
  ))

# length per age all measurements ----
length_all<-ggplot(age_calc%>%filter(!is.na(length_use)), aes(x = age_month, y = length_use, shape = POD, color = age_value))+
  geom_point()+
  theme_bw()+
  theme(legend.position = "bottom")+
  xlab("Age")+
  ylab("Length (m)")

length_all

num_measurements<-nrow(age_calc)
num_individuals_measured<-age_calc%>%
  distinct(ID)%>%
  nrow()

## connect the dots for individual
ID_pertrip_pod<-length_all+
  geom_line(aes(group = ID))

ID_pertrip_pod

# length per age per trip ----
length_trip<-ggplot(age_calc, aes(x = age_month, y = length_use, color = POD))+
  geom_point()+
  facet_wrap(~trip)+
  theme_bw()+
  theme(legend.position = "bottom")+
  xlab("Age")+
  ylab("Length (m)")

length_trip

age_calc%>%distinct(ID, POD)%>%group_by(POD)%>%tally()

ggsave("./Figures/length_trip.png", length_trip, dpi = 320, height = 100, units = 'mm')

#age_calc%>%filter(n>1)%>%mutate(CV = actual_length_sd/actual_length_mean)%>%group_by(trip)%>%summarise(min = min(CV),max=max(CV), mean_CV=mean(CV), n = n())

# Individuals that have been measured on more than one trip ----
ID_age<-age_calc%>%
  group_by(ID)%>%
  mutate(n = n())%>%
  filter(n > 1)%>%
  arrange(ID,trip)%>%
  mutate(length_diff = lead(length_use) - length_use)
  
individuals_measuredmanytimes<-ggplot(ID_age, aes(x = trip, y = length_use, color = SEX))+
  geom_point()+
  facet_wrap(~ID, ncol = 7)+
  theme(legend.position = "bottom")

individuals_measuredmanytimes

ggsave("./Figures/individuals_measuredmanytimes.png", individuals_measuredmanytimes, dpi = 320, height = 500, width = 500, units = 'mm')                                                                                                                                         
```
```{r vbgc, include = T, warning=FALSE, message=FALSE}

# data for VBGC

age_vbgc<-age_calc%>%
  filter(!is.na(length_use))%>%
  dplyr::rename("length" = "length_use")

# fitting von Bertalanffy ----
# https://rpubs.com/lacs/1123

# van Bertalanffy
theta <- c(3, 0.2, 1)

SSQ <- function(theta, x) {
    Linf <- theta[1]
    K <- theta[2]
    t0 <- theta[3]
    epsilon <- rep(0, nrow(age_vbgc))
    lpred <- rep(0, nrow(age_vbgc))
    for (i in 1:nrow(age_vbgc)) {
        lpred[i] <- Linf * (1 - exp(-K * (age_vbgc$age_month[i] - t0)))
        epsilon[i] <- (age_vbgc$length[i] - lpred[i])^2 #difference between estimate and measured, squared for logistic
        }
    ssq <- sum(epsilon)
    return(ssq)
}


out <- optim(theta, fn = SSQ, method = "BFGS", x = age_vbgc$age, hessian = TRUE)
out$V <- solve(out$hessian)  #solve the hessian
out$S <- sqrt(diag(out$V))  #Standard Error
out$R <- out$V/(out$S %o% out$S)  #Correlation

out

lp <- out$par[1] * (1 - exp(-out$par[2] * (age_vbgc$age - out$par[3])))

lpdf<-as.data.frame(lp)

age_vbgc_curve<-age_vbgc%>%
  bind_cols(curve = lpdf$lp)

## length per year age

Linf_o<-out$par[1]
K_o<-out$par[2]
t0_o<-out$par[3]

ggplot(age_vbgc_curve)+
  geom_point(mapping = aes(x = age_month, y = length, color = age_value))+
  stat_function(fun=function(x)(Linf_o * (1 - exp(-K_o * (x - t0_o)))))+
  theme(legend.position = "bottom")+
  xlab("Age")+
  ylab("Mean length (m)")+
  theme_bw()+
  ylim(c(-0.2,3.5))+
  xlim(c(-6, max(age_vbgc_curve$age)))

age_vbgc_curve%>%
  filter(ID == "COMET")%>%
  mutate(age_est = (1/-K_o)*log(1-(length/Linf_o))+ t0_o,
  age_diff = age_est - age)%>%
  arrange(age_diff)%>%
  dplyr::select(ID, age, age_est, age_diff)

#doesnt work when length > Linf_o
#length<-Linf_o-0.00000001
#solve for age from Length
#(1/-K_o)*log(1-(length/Linf_o))+ t0_o
```
```{r, vbgc_bayes}
##leah's attempt at building models in Nimble
# https://r-nimble.org/html_manual/cha-writing-models.html
library(nimble);library(rstan)

age_vbgc<-age_calc%>%
  filter(!is.na(length_use))%>%
  dplyr::rename("length" = "length_use")

head(age_vbgc)

n = nrow(age_vbgc)

model<-nimble::nimbleCode({

for (i in 1:n){ 
  
    #likelihood

    # y = y[i](t[j]) eq. 1 observed length
    # x = g[i](t[j]) = predicted length/growth curve
    
    #log(Linf) ~ T(dnorm(mu, sd = sigma), 0, Inf)
    #log(K) ~ T(dnorm(mu, sd = sigma), 0, Inf)
    #log(to+10) ~ T(dnorm(mu, sd = sigma), 0, Inf)
    
    #Schofield et al. 2013 eq. 1
    y[i] ~ T(dnorm(x[i], tau.y), 0, Inf)    
    #Schofield et al. 2013 eq. 3
    x[i] <- Linf*(1 - K^(age[i] - t0))
   
    #Midway et al. 2015
     #y[i] ~ dnorm(y.hat[i], tau.y)
     #y.hat[i] <- Linf *(1 - exp(-K *(age[i] - t0)))

}  
  #prior
  
  #Midway et al. 2015
  tau.y <- pow(sigma_y, -2)
  sigma_y ~ dunif(0, 100)
  
  Linf ~ dnorm(3, 0.4)
  K ~ dunif(0, 1)
  t0 ~ dnorm(-2.5, 0.5)


})

inits_fun = function(){
  
  K_init = 0.5
  t0_init = -2.5
  
  return(list(K = K_init, t0 = t0_init))

}
#Midway
#params = c("Linf", "K", "t0", "sigma_y", "y.hat")
#Schofield
params = c("Linf", "K", "t0", "sigma_y")

data = list(y = as.numeric(age_vbgc$length), 
            age = as.numeric(age_vbgc$age_month))

samples<-nimble::nimbleMCMC(code = model,
                            constants = list(n = n),
                            data = data,
                            inits = inits_fun(),
                            niter = 10000,
                            nburnin = 1000, 
                            nchains = 3,
                            monitors = params,
                            samplesAsCodaMCMC = T
                            )

coda.samples<-coda::mcmc(samples)
#### ppm ----- 
#another way to code the above
# Rmodel <- nimble::nimbleModel(code = model, 
#                               constants = list(n = n),
#                               data = data, 
#                               inits = inits_fun())
# 
# cmodel<-nimble::compileNimble(Rmodel)
# mcmc<-buildMCMC(Rmodel, monitors = params)
# cmcmc   <- compileNimble(mcmc, project = Rmodel)
# samples <- runMCMC(cmcmc, niter = 10000, nburnin = 1000, nchains = 3, samplesAsCodaMCMC = T)

### -----

summ<-summary(samples)
summ
summ$statistics[1]
summ$quantiles[c(1,5)]

bayesplot::mcmc_trace(coda.samples)
coda::gelman.diag(coda.samples)


ggplot()+
  geom_histogram(mapping = aes(x = as.matrix(samples), y=..density..), bins = 100, color = "black", alpha = 0.8)+
  geom_density(mapping = aes(x = as.matrix(samples)), color = "black")+
  theme_bw()+
  xlab("Linf")+
  xlim(c(0,1))


samples.df<-as.data.frame(as.matrix(samples))
               
ggplot()+
  geom_histogram(mapping = aes(x = samples.df$Linf, y=..density..), bins = 30, color = "black", alpha = 0.8)+
  geom_density(mapping = aes(x = samples.df$Linf), color = "black")+
  theme_bw()

ggplot()+
  geom_histogram(mapping = aes(x = samples.df$K, y=..density..), bins = 30, color = "black", alpha = 0.8)+
  geom_density(mapping = aes(x = samples.df$K), color = "black")+
  theme_bw()

ggplot()+
  geom_histogram(mapping = aes(x = samples.df$t0, y=..density..), bins = 30, color = "black", alpha = 0.8)+
  geom_density(mapping = aes(x = samples.df$t0), color = "black")+
  theme_bw()

#### https://r-nimble.org/nimbleExamples/posterior_predictive.html ----
samples.df<-as.data.frame(as.matrix(samples))

dataNodes <- Rmodel$getNodeNames(dataOnly = TRUE)
parentNodes <- Rmodel$getParents(dataNodes, stochOnly = TRUE)  # `getParents` is new in nimble 0.11.0
## Ensure we have both data nodes and deterministic intermediates (e.g., lifted nodes)
simNodes <- Rmodel$getDependencies(parentNodes, self = FALSE)


nSamp <- nrow(samples.df)
ppSamples <- matrix(0, nSamp, n)

ppSamples <- matrix(0, nrow = nSamp, ncol =
          length(Rmodel$expandNodeNames(dataNodes, returnScalarComponents = TRUE)))

postNames <- colnames(samples$chain1)

# posterior predictive sampling takes ages

# set.seed(1)
# system.time({
# for(i in 1:nSamp) {
#   
#     values(cmodel, postNames) <- samples.df[i, ]  # assign 'flattened' values
#     cmodel$simulate(simNodes, includeData = TRUE)
#     ppSamples[i, ] <- values(cmodel, dataNodes)
# }
# })

#obsMin <- min(data$y)
#ppMin <- apply(ppSamples, 1, min)

# ## Check with plot in Gelman et al. (3rd edition), Figure 6.3
# hist(ppMin, xlim = c(-50, 20),
#     main = "Discrepancy = min(y)", 
#     xlab = "min(y_rep)")
# abline(v = obsMin, col = 'red')
# 
# ppSamples

summ$statistics

K_mean<-summ$statistics[1]
Linf_mean<-summ$statistics[2]
t0_mean<-summ$statistics[4]

ggplot(age_vbgc)+
  geom_point(mapping = aes(x = age_month, y = length, color = age_value))+
  stat_function(fun=function(x)(Linf_mean * (1 - exp(-K_mean * (x - t0_mean)))))+
  theme(legend.position = "bottom")+
  xlab("Age")+
  ylab("Mean length (m)")+
  theme_bw()+
  ylim(c(-0.2,3.5))+
  xlim(c(-6, max(age_vbgc_curve$age)))


```
```{r, vbgc_bayes_heir}
##leah's attempt at building models in Nimble
# https://r-nimble.org/html_manual/cha-writing-models.html
library(nimble);library(rstan)

age_vbgc<-age_calc%>%
  filter(!is.na(length_use))%>%
  dplyr::rename("length" = "length_use")%>%
  mutate(m_1 = case_when(
    SEX == "M" ~ 1,
    TRUE ~ 0
  ))%>%
  group_by(ID)%>%
  mutate(n = n())

head(age_vbgc)

age_vbgc_IDlist<-split(age_vbgc, age_vbgc$ID)
length(age_vbgc_IDlist)


model<-nimble::nimbleCode({
  
for(i in 1:length(age_vbgc_IDlist)){
  
  for(j in 1:nrow(age_vbgc_IDlist[i])){
    #likelihood

    # y = y[i](t[j]) eq. 1 observed length
    # x = g[i](t[j]) = predicted length/growth curve
    
    #log(Linf) ~ T(dnorm(mu, sd = sigma), 0, Inf)
    #log(K) ~ T(dnorm(mu, sd = sigma), 0, Inf)
    #log(to+10) ~ T(dnorm(mu, sd = sigma), 0, Inf)
    
    #Schofield et al. 2013 eq. 1
    y[j] ~ T(dnorm(x[j], sigma_y), 0, Inf)    
    
    #heirarchical
    Linf[i] ~ T(dnorm(beta_l0 + (beta_l1 * m_1[i]), sigma_l), 0, Inf)
    logit(k[i]) ~ dnorm(beta_k0 * (1 - m_1[i]) + beta_k1*m_1[i], sigma_k) 
    
    #E[i] ~ dnorm(0, sigma)
    #Schofield et al. 2013 eq. 3
    x[j] <- Linf[i]*(1 - K^(age[j] - t0)) #+ E[i]
   
  }
}

  #prior
  sigma_y ~ T(dt(mu = 0, tau = 2500), 0, Inf) #truncated student t distribution
  beta_l0 ~ dnorm(0, 1000^2)
  beta_l1 ~ dnorm(0, 1000^2)
  sigma_l ~ T(dt(mu = 0, tau = 2500), 0, Inf) #truncated student t distribution
  beta_k0 ~ dlogis(0, 1)
  beta_k1 ~ dlogis(0, 1)
  sigma_k ~ T(dt(mu = 0, tau = 25), 0, Inf) #truncated student t distribution

})

inits_fun = function(){
  
  K_init = rlnorm(1)
  t0_init = rlnorm(1)
  
  return(list(K = K_init, t0 = t0_init))

}

params = c("Linf", "K", "t0")

samples<-nimble::nimbleMCMC(code = model,
                            #constants = list(n = n),
                            data = list(y = as.numeric(age_vbgc_IDlist[[i]]$length), 
                                        age = as.numeric(age_vbgc_IDlist[[i]]$age_month),
                                        m_1 = as.numeric(age_vbgc_IDlist[[i]]$m_1)),
                            inits = inits_fun(),
                            niter = 10000,
                            nburnin = 1000, 
                            nchains = 3,
                            monitors = params,
                            samplesAsCodaMCMC = T
                            )

coda.samples<-coda::mcmc(samples)

summ<-summary(samples)
summ
summ$statistics[1]
summ$quantiles[c(1,5)]

bayesplot::mcmc_trace(coda.samples)
coda::gelman.diag(coda.samples)

bayesplot::mcmc_areas(as.matrix(samples),
           pars = params,
           prob = 0.8) 

samples.df<-as.data.frame(as.matrix(samples))
               
ggplot()+
  geom_histogram(mapping = aes(x = samples.df$Linf, y=..density..), bins = 30, color = "black", alpha = 0.8)+
  geom_density(mapping = aes(x = samples.df$Linf), color = "black")+
  theme_bw()

## need to write this for NIMBLE specifically: https://r-nimble.org/nimbleExamples/posterior_predictive.html

as.data.frame(as.matrix(samples))

nSamp <- nrow(as.matrix(samples))
ppSamples <- matrix(0, nSamp, n)

set.seed(1)
for(i in 1:nSamp){
  model[["Linf"]] <- samples[i, "Linf"]             ## or cmodel$mu <- samples[i, "mu"]
  model[["K"]] <- samples[i, "K"]
  model$simulate(simNodes, includeData = TRUE)
  ppSamples[i, ] <- model[["y"]]
}


ppSamples <- matrix(0, nrow = nSamp, ncol =
          length(model$expandNodeNames(dataNodes, returnScalarComponents = TRUE)))
postNames <- colnames(samples)

set.seed(1)
system.time({
for(i in seq_len(nSamp)) {
    values(cmodel, postNames) <- samples[i, ]  # assign 'flattened' values
    cmodel$simulate(simNodes, includeData = TRUE)
    ppSamples[i, ] <- values(cmodel, dataNodes)
}
})

```
```{r, BayesGrowth}
#Leah using assists
#https://github.com/jonathansmart/BayesGrowth
library(BayesGrowth)

age_vbgc<-age_calc%>%
  filter(!is.na(length_use))%>%
  dplyr::rename("length" = "length_use")%>%
  dplyr::select("Age" = "age_month", "Length" = "length")%>%
  #mutate(Length = as.integer(Length*1000))%>%
  as.data.frame(row_number())
  
plot(age_vbgc)
head(age_vbgc)
summary(age_vbgc)

age_vbgc%>%
  filter(is.na(Length))

#data("example_data")
#head(example_data)
#summary(example_data)

max_size <- max(age_vbgc$Length)
max_size_se <- sd(age_vbgc$Length)/sqrt(length(age_vbgc$Length))
birth_size <- 0
birth_size_se <- 0.015

# Use the function to estimate the rstan model
fit <- Estimate_MCMC_Growth(data = age_vbgc, 
                            Model = "VB" ,
                            iter = 10000,
                            BurnIn = 1000,
                            n.chains = 4,
                            Linf = max_size,
                            Linf.se = max_size_se,
                            L0 = birth_size,
                            sigma.max = 10,
                            L0.se = birth_size_se,
                            k.max = 1)

pairs(fit, pars = c("Linf", "k","L0", "sigma"))

list_of_draws <- extract(fit,c("Linf", "k","L0", "sigma")) %>% 
  as.data.frame() %>% 
  tidyr::gather(Parameter, Value) %>% 
  filter(Parameter %in% c("Linf", "k","L0", "sigma"))


ggplot(list_of_draws, aes(Value))+
  geom_density(fill = "royalblue")+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  theme_bw()

library(tidybayes)

# Return a growth curve with 50th and 95th percentiles
growth_curve <- Calculate_MCMC_growth_curve(fit, Model = "VB",
                                            max.age = max(age_vbgc$Age), probs = c(.5,.95))


ggplot()+
  stat_function(age_vbgc_curve, mapping = aes(x = age_month, y = length), color = "red", size = 2, fun=function(x)(Linf_o * (1 - exp(-K_o * (x - t0_o)))))+
  stat_function(age_vbgc, mapping = aes(x = Age, y = Length), color = "blue", fun=function(x)(Linf_mean * (1 - exp(-K_mean * (x - t0_mean)))))+
  geom_point(data = age_vbgc, aes(Age, Length), alpha = .3)+
  geom_lineribbon(growth_curve,mapping =  aes(x = Age, y = LAA, ymin = .lower, ymax = .upper, fill = factor(.width)), size = .8) +
  labs(y = "Total Length (mm)", x = "Age (yrs)")+
  scale_fill_brewer(palette="YlOrRd", direction=-1,name = "Credibility interval")+
  scale_y_continuous(expand = c(0,0))+
  xlim(c(-3,42))+
  #scale_x_continuous(expand = c(0,1), breaks = seq(-5,50,5))+
  theme_bw()+
  theme(text = element_text(size = 14),
        legend.position = c(0.8,0.2),
        legend.background = element_rect(colour = "black"))


ggplot()+
  #geom_point(age_vbgc_curve, mapping = aes(x = age_month, y = length, color = age_value))+
  stat_function(age_vbgc_curve, mapping = aes(x = age_month, y = length), color = "red", fun=function(x)(Linf_o * (1 - exp(-K_o * (x - t0_o)))))+
  theme(legend.position = "bottom")+
  xlab("Age")+
  ylab("Mean length (m)")+
  theme_bw()+
  ylim(c(-0.2,3.5))+
  xlim(c(-6, max(age_vbgc_curve$age)))

```

```{r, scotland_comparison, include = F}

mean_year_age<-mean_year_age_noid+
  geom_line(aes(group = ID))

##
mean_year_age_scotland<-ggplot()+
  geom_point(data = age_calc_year_mean, mapping = aes(x = age, y = actual_length_mean_mean))+
  #geom_smooth()+
  theme(legend.position = "bottom")+
  theme_bw()+
  xlab("Age")+
  ylab("Mean length (m)")+
  geom_vline(xintercept = c(1,3,5,9), color = "orange")+
  geom_point(mapping = aes(x=c(0.5,2,4,7,20), y=c(1.39,2.43,2.75,2.86,3.06)), color = "orange", size = 3, shape = 17)

#age_calc_month%>%filter(ID == 'SPLASH')

ggsave("./Figures/mean_year_age.png", mean_year_age, dpi = 320, height = 100, units = 'mm')
ggsave("./Figures/mean_year_age_scotland.png", mean_year_age_scotland, dpi = 320, height = 100, units = 'mm')

#growth/shrinking
age_calc_year_mean%>%
  arrange(ID, age)%>%
  group_by(ID)%>%
  mutate(growth = lead(actual_length_mean_mean)-actual_length_mean_mean)%>%
  filter(!is.na(growth))%>%
  arrange(age)
```
\newpage

Fig. 2: Each point represents the mean total length of an individual at its age for animals whose birth year is known.

```{r summary_stats_ageclass, include = F}
age_length%>%
  group_by(trip, AGECLASS)%>%
  mutate(actual_length_mean_agg = mean(actual_length_mean), #mean of lengths measured using altitude at exact time
         actual_length_sd_agg = sd(actual_length_mean), #sd of lengths measured using altitude at exact time
         actual_length_range = paste0(round(min(actual_length_mean),2),'–',round(max(actual_length_mean), 2)),
         num_ind = n())%>%
  distinct(trip, AGECLASS, actual_length_mean_agg, actual_length_sd_agg, actual_length_range, num_ind)
```

```{r ageclass_boxplots, echo = F}

ageclass_length_peryear<-age_length%>%
  filter(!is.na(AGECLASS))%>%
  group_by(ID, YEAR)%>%
  mutate(actual_length_mean_mean = mean(as.numeric(actual_length_mean), na.rm = T), #mean of lengths measured using altitude at exact time
         actual_length_mean_sd = sd(as.numeric(actual_length_mean), na.rm = T), #sd of lengths measured using altitude at exact time
         n = n())%>%
  distinct(ID, AGECLASS, n, SEX, BIRTH_YEAR, FIRST_YEAR, POD, YEAR, actual_length_mean_mean, actual_length_mean_sd) 


ageclass<-ggplot(ageclass_length_peryear, aes(x=AGECLASS, y=actual_length_mean_mean))+
  geom_boxplot(aes(fill = AGECLASS), color = "black", alpha = 0.5)+
  #geom_boxplot(aes(x=AGECLASS, y = actual_length_mean_mean, color = POD, fill = POD), alpha = 0.5, varwidth = T)+
  theme(legend.position = "bottom")+
  xlab("Age class")+
  ylab("Length (m)")+
  theme_bw()+
  scale_fill_viridis_d()

```

Fig. 3: Summary of total lengths (m) per age-class. C = calf of the year, J = 1-2 y, S-A = 3-8, A = 9+.

```{r agesex_boxplots, echo = F}

sex<-ggplot(ageclass_length_peryear, aes(x=AGECLASS, y=actual_length_mean_mean))+
  geom_boxplot(aes(fill = AGECLASS),color = "black", alpha = 0.5)+
  #geom_boxplot(aes(x=AGECLASS, y=actual_length_mean_mean, color = POD, fill = POD), alpha = 0.5, varwidth = T)+
  facet_wrap(~SEX)+
  theme(legend.position = "bottom")+
  xlab("Age class")+
  ylab("")+
  theme_bw()+
  scale_fill_viridis_d()

ageclass_length_peryear%>%
  filter(actual_length_mean_mean > 3)

# ageclass_length_peryear%>%
#   ungroup()%>%
#   distinct(ID, SEX, POD)%>%
#   group_by(SEX, POD)%>%
#   filter(SEX == "X")%>%
#    tally()
# 
# agesex_length_peryear%>%
#   filter(ID == "COMET")


box_plot<-ggpubr::ggarrange(ageclass,sex, common.legend = T, widths = c(0.3, 0.7), legend = "bottom")

ggsave("./Figures/box_plot.png", box_plot, dpi = 320, height = 100, width = 250, units = 'mm')

```

Fig. 4: Summary of total lengths (m) per sex and age-class. C = calf of the year, J = 1-2 y, S-A = 3-8, A = 9+. F = female, M = male, X = unknown.

```{r, stats}

ageclass_length_peryear%>%
  filter(actual_length_mean_mean>3)%>%
  arrange(actual_length_mean_mean)


measurement_ID_trip%>%
  filter(ID == 'MENTRY')

```


```{r measure_per_individual, echo = F}

# sluething suspect measurements
ggplot(length_ID_merge_Tt)+
  geom_point(aes(x = actual_length_mean_mean, y = actual_length_mean_sd))

hist<-ggplot(length_ID_merge_Tt%>%group_by(ID,trip)%>%tally())+
  geom_histogram(aes(x = n), binwidth = 1, color = "black")+
  facet_wrap(~trip)+
  ylab("Number of individuals")+
  xlab("Number of photographs measured")+
  theme_bw()

hist

# length_ID_merge_Tt%>%
#   filter(is.na(actual_length))

ggsave("./Figures/hist.png", hist, dpi = 320, height = 75, units = 'mm')

length_ID_merge_Tt%>%ungroup()%>%distinct(ID, POD)%>%filter(!is.na(POD))%>%group_by(POD)%>%tally()

```

Fig. 1: number of times individuals were measured per trip
